"""add datetime

Revision ID: 50bc7d8f937a
Revises: db7285025046
Create Date: 2024-12-22 20:07:06.581939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bc7d8f937a'
down_revision: Union[str, None] = 'db7285025046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_purchases', 'purchase_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'purchases',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'recommendations',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'recommendations',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'purchases',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_purchases', 'purchase_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
